### ISSUE TITLE
Button "open" opens in wrong program

### ISSUE THREAD

**Issue by caco3** [ricardomv/snapper-gui#17]
In which program is a snapshot supposed to be "opened"?
I select a snapshot, then press "open". Then **audacious** gets started with a playlist containing a lot of (non music) files. When I remove audacious, **EasyTAG** gets started instead.

Both programs do not make any sense for the function "open".
Which program is supposed to be started?
This might be a misconfiguration of the systems file type to program allocation, but for which file types?

**Comment by ricardomv** [comment]
It uses xdg-open to find the default application for opening files, in my case it uses gnome files as it should, there might be a way to change the default application but it depends on on your system.

**Comment by caco3** [comment]
Thank you for the info.
It seems to be related to sudo. When using that `sudo xdg-open <folder>` a wrong program gets opened. But when using su and then `xdg-open <folder>`, it works fine.
