### ISSUE TITLE
Package failes to build

### ISSUE THREAD

**Issue by huegelc** [ricardomv/snapper-gui#18]
Package failes to build on arch linux:

`==> Starting pkgver()...
fatal: No names found, cannot describe anything.
==> ERROR: pkgver is not allowed to be empty.
==> ERROR: pkgver() generated an invalid version: 
==> ERROR: Makepkg was unable to build .
==> Restart building snapper-gui-git ? [y/N]
==> ----------------------------------------
==> n
`

**Comment by ricardomv** [comment]
This was not really a issue with the code but with the PKGBUILD but it should be fixed by releasing v0.1.
