### ISSUE TITLE
How to execute snapper-gui after installing?

### ISSUE THREAD

**Issue by MurzNN** [ricardomv/snapper-gui#5]
I have successfully install snapper-gui via installation manual on Ubunut, but don't understand what to do next.

How to run this app after installing? I can't find any executable file in /usr/local/bin or in other folders.

Can you extend README.md via examples how to find and execute snapper-gui binary?

And will be good to see some screenshots in front page of snapper-giu github page, for understanding what users got after installing. Can you add example images? 

Thanks.

**Comment by ricardomv** [comment]
After running `sudo python3 setup.py develop` you should be able to just run `snapper-gui`. I have also updated the readme with screenshots.

**Comment by MurzNN** [comment]
Thanks for the screenshots, but I can't run it:
$ snapper-gui
snapper-gui: command not found
$ sudo snapper-gui
sudo: snapper-gui: command not found

Maybe I miss some packages for run this app?

System is Ubuntu 14.10 AMD64, and here is output of install process: 
> $ sudo python3 setup.py install
> /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'entry_points'
>   warnings.warn(msg)
> running install
> running build
> running build_py
> creating build
> creating build/lib
> creating build/lib/snappergui
> copying snappergui/__init__.py -> build/lib/snappergui
> copying snappergui/application.py -> build/lib/snappergui
> copying snappergui/changesWindow.py -> build/lib/snappergui
> copying snappergui/createConfig.py -> build/lib/snappergui
> copying snappergui/createSnapshot.py -> build/lib/snappergui
> copying snappergui/deleteDialog.py -> build/lib/snappergui
> copying snappergui/mainWindow.py -> build/lib/snappergui
> copying snappergui/propertiesDialog.py -> build/lib/snappergui
> copying snappergui/snapshotsView.py -> build/lib/snappergui
> creating build/lib/snappergui/glade
> copying snappergui/glade/changesWindow.glade -> build/lib/snappergui/glade
> copying snappergui/glade/createConfig.glade -> build/lib/snappergui/glade
> copying snappergui/glade/createSnapshot.glade -> build/lib/snappergui/glade
> copying snappergui/glade/deleteSnapshot.glade -> build/lib/snappergui/glade
> copying snappergui/glade/mainWindow.glade -> build/lib/snappergui/glade
> copying snappergui/glade/propertiesDialog.glade -> build/lib/snappergui/glade
> copying snappergui/glade/snapshotsView.glade -> build/lib/snappergui/glade
> creating build/lib/snappergui/icons
> copying snappergui/icons/snappergui.svg -> build/lib/snappergui/icons
> creating build/lib/snappergui/ui
> copying snappergui/ui/app-menu.ui -> build/lib/snappergui/ui
> running install_lib
> running install_egg_info
> Removing /usr/local/lib/python3.4/dist-packages/snappergui-0.1.egg-info
> Writing /usr/local/lib/python3.4/dist-packages/snappergui-0.1.egg-info


Where can be the problem?

**Comment by ricardomv** [comment]
Do you have python-setuptools installed?

**Comment by MurzNN** [comment]
No, python-setuptools is not installed, now I install it, but it isn't help:

$ sudo aptitude install python-setuptools

$ sudo python3 setup.py install
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python3.4/dist-packages/snappergui-0.1.egg-info
Writing /usr/local/lib/python3.4/dist-packages/snappergui-0.1.egg-info

$ snapper-gui
snapper-gui: command not found


Maybe I need to add some folders to PATH variable?

**Comment by MurzNN** [comment]
Installing python3-setuptools package on Ubuntu solves the problem with installing snapper-gui, now snapper-gui runs, but show errors:
$ snapper-gui
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/snapper-gui", line 9, in <module>
    load_entry_point('snappergui==0.1', 'gui_scripts', 'snapper-gui')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/application.py", line 3, in <module>
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/mainWindow.py", line 7, in <module>
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/changesWindow.py", line 3, in <module>
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name GtkSource, introspection typelib not found


I will try to google about them and fix with myself.

**Comment by ricardomv** [comment]
No, it's just not findig the entry points (see the warning) that are used to create the executable. I will see what i can do when i get to a computer.

**Comment by MurzNN** [comment]
This error solved via http://stackoverflow.com/questions/21064163/what-do-i-have-to-install-to-resolve-could-not-find-any-typelib-for-gtksource-c 
so I install additional packages:
$ sudo apt-get install gir1.2-gtksource-3.0

After this something is run, but I did'nt see any gui, only this output in console:
$ sudo snapper-gui

(snappergui:653): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:59:16: Theming engine 'adwaita' not found

(snappergui:653): Gtk-WARNING **: Child name 'root' not found in GtkStack
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/application.py", line 58, in do_activate
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/mainWindow.py", line 59, in __init__
KeyError: 'root'

**Comment by ricardomv** [comment]
Thats actually an issue i need to fix. You have to create a default config with snapper cli that will be named root

**Comment by ricardomv** [comment]
@MurzNN do you still have any issues that need to be solved?

**Comment by MurzNN** [comment]
Today I clone current fresh git repo, compile it via `sudo python3 setup.py develop`, but see same error after run:

$ sudo snapper-gui

(snappergui:6193): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:59:16: Theming engine 'adwaita' not found

(snappergui:6193): Gtk-WARNING **: Child name 'root' not found in GtkStack
Traceback (most recent call last):
  File "/home/korepov/temp/2015-05/snapper-gui/snapper-gui/snappergui/application.py", line 58, in do_activate
    self._window = SnapperGUI(self)
  File "/home/korepov/temp/2015-05/snapper-gui/snapper-gui/snappergui/mainWindow.py", line 59, in __init__
    self.statusbar.push(5,"%d snapshots"% self.configView["root"].count)
KeyError: 'root'

**Comment by ricardomv** [comment]
@MurzNN you need to create a configuration named root (that's the default) with snapper cli. I will patch this in the future so that it works without any configuration.

**Comment by njzhaopei** [comment]
I got the same error >

(snappergui:10859): Gtk-WARNING **: Child name 'root' not found in GtkStack
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/application.py", line 58, in do_activate
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/mainWindow.py", line 59, in __init__
KeyError: 'root'

what does "create a configuration named root (that's the default) with snapper cli" mean ?

**Comment by msx** [comment]
@njzhaopei 
Fire up a terminal, become root and ```# snapper -c root create-config /```
You can read more about snapper at snapper.io or check both the Arch Linux and OpenSUSE wiki articles for further reference.

**Comment by njzhaopei** [comment]
Thank for your replying. Originally I just want to see the GUI ,then I modified a python file and it works for me(though appear "key error"). I think this way ' snapper -c root create-config /' will help me solve all the problems.

**Comment by tkSimon** [comment]
I have dual boot on my laptop, with opensuse and fedore, both installed to the same btfs volume, in different subvolumes. My intention was to have 3 configs:
* OpenSUSE
* Fedora
* home
Basically, no config named root. Are there any plans on getting this root config requirement removed?

**Comment by ricardomv** [comment]
@tkSimon Should be fixed now. Removed the statusbar message because it shouldn't be done from there anyway.

**Comment by MurzNN** [comment]
Thanks, at now Snapper GUI starts normally, here is good manual how to install it on Ubuntu: https://poisonpacket.wordpress.com/2015/06/04/installing-btrfs-snapper-gui-on-ubuntu-and-ubuntu-derivatives/
