### ISSUE TITLE
SnapperGUI doesn't work unless called as sudo

### ISSUE THREAD

**Issue by jaysonwcs** [ricardomv/snapper-gui#50]
I'm using Kubuntu, and AFAIK it's not possible to open GUI apps as sudo (kdesu and gksu are not available anymore).

Error when tried to create a snapshot:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/snappergui/mainWindow.py", line 94, in on_create_snapshot
    newSnapshot = snapper.CreateSingleSnapshot(dialog.config,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: error.no_permissions: org.freedesktop.DBus.Error.Failed

Is there a way to ask for password instead of executing as sudo?

**Comment by dsvi** [comment]
in the snapper config at`/etc/snapper/configs` add
ALLOW_USERS="jaysonwcs"
Also make the config itself readable by yourself

**Comment by jaysonwcs** [comment]
Sorry, I didn't read the full manual for the original Snapper CLI tool. You can close the issue.
