### ISSUE TITLE
Changes window does not open

### ISSUE THREAD

**Issue by PrMinisterGR** [ricardomv/snapper-gui#8]
Hello there. I have installed the package in Arch Linux, but the functionality is not complete. I get a list of the snapshots, but the Userdata pane is empty no matter if I have a snapshot selected or not, and the Changes button does nothing, no matter if I have something selected or not.

This is the pkgbuild:
http://pastebin.com/raw.php?i=EaXWAaNt

This is the screenshot (I have opened the gui through the terminal, it does exactly the same if I run it as root).

http://i.imgur.com/7Qx4WZh.png

**Comment by ricardomv** [comment]
Hi, to have userdata in a snapshot you need to use the command line option `--userdata` or add it manually when you create a new one using the gui, in your case those are timeline snapshots so they don't have userdata. To have the list of changed files you might need to start snapper-gui as root depending on your configuration.

**Comment by ybznek** [comment]
I have the issue too on my Manjaro(Arch based). I run ```sudo snapper-gui```, but nothing happens when I click on "changes" button.

**Comment by MurzNN** [comment]
Moved from my issue:
I got same problem on Ubuntu, but with other console output. I run `sudo snapper-gui` via root too, and on click "Changes" in console see the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/mainWindow.py", line 160, in on_viewchanges_clicked
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/changesWindow.py", line 10, in __init__
NameError: name 'GObject' is not defined
```
In thread http://ubuntuforums.org/showthread.php?t=1548407 user recommend to add `import gobject` line to code, maybe this fix the problem? But I can't find in which file and place I must add this.

**Comment by MurzNN** [comment]
Thanks, this patch fix the problem!
